//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Categories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRank
    {
        public int idUserRank { get; set; }
        public string CodeRank { get; set; }
        public string DescRank { get; set; }
    }
}
